name: Release-PR
on:
  issue_comment:
    types: [created]

jobs:
  Release-PR:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.author_association == 'OWNER' &&
      startsWith(github.event.comment.body, '/workflows/release-pr')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Read VERSION into VERSION
        run: echo ::set-output name=VERSION::$(cat VERSION)
        id: version

      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Building ${{steps.version.outputs.VERSION}} Release PR...'
            })

      - name: Read .nvmrc into NVMRC
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile

      - name: Set Git Identity
        run: |
          git config --global user.name 'release-bot'
          git config --global user.email 'release-bot@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply VERSION & Commit
        run: yarn run version:apply --yes

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update v${{ steps.version.outputs.VERSION }}"
          committer: GitHub <noreply@github.com>
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: 'v${{ steps.version.outputs.VERSION }}'
          body: |
            ## v${{ steps.version.outputs.VERSION }}

            ### Breaking Changes

            - [ ] TODO

            ### Features

            - [ ] TODO

            ### Bug Fixes

            - [ ] TODO
          labels: "Web3API-Release"
          branch: "release/${{ steps.version.outputs.VERSION }}"
          request-to-parent: false

      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**Release PR Created:** https://github.com/${{ github.repository }}/pull/${{ steps.cpr.outputs.pr_number }}'
            })
