name: Release-PR
on:
  issue_comment:
    types: [created]

jobs:
  Release-PR:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.author_association == 'OWNER' &&
      startsWith(github.event.comment.body, '/workflows/release-pr')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Read VERSION into env.RELEASE_VERSION
        run: echo RELEASE_VERSION=$(cat VERSION) >> $GITHUB_ENV

      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.WEB3_API_BUILD_BOT_PAT}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**Building Release PR (`${{env.RELEASE_VERSION}}`):** https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}'
            })

      - name: Read .nvmrc into env.NVMRC
        run: echo NVMRC=$(cat .nvmrc) >> $GITHUB_ENV

      - name: Set env.USER to User
        run: echo USER=web3-api-build-bot >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{env.NVMRC}}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile

      - name: Set Git Identity
        run: |
          git config --global user.name '${{env.USER}}'
          git config --global user.email '${{env.USER}}@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.WEB3_API_BUILD_BOT_PAT }}

      - name: Apply Version & Commit
        run: yarn run version:apply --yes

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WEB3_API_BUILD_BOT_PAT }}
          push-to-fork: ${{env.USER}}/${{github.event.repository.name}}
          branch: release/${{env.RELEASE_VERSION}}
          base: ${{ github.event.pull_request.base.ref }}
          committer: GitHub <noreply@github.com>
          author: ${{env.USER}} <${{env.USER}}@users.noreply.github.com>
          commit-message: "${{env.RELEASE_VERSION}}"
          title: 'Web3API ${{env.RELEASE_VERSION}}'
          body: |
            ## Web3API ${{env.RELEASE_VERSION}}

            TODO: Add "Web3API-Release" Label

            ### Breaking Changes

            - [ ] TODO

            ### Features

            - [ ] TODO

            ### Bug Fixes

            - [ ] TODO

      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.WEB3_API_BUILD_BOT_PAT}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**Release PR Created (`${{env.RELEASE_VERSION}}`):** https://github.com/${{env.USER}}/${{github.event.repository.name}}/pull/${{ steps.cpr.outputs.pull-request-number }}'
            })
